### ISSUE TITLE
Find mirrors for psprint's ZSH plugins

### ISSUE THREAD

**Issue by unixorn** [unixorn/awesome-zsh-plugins#1332]
psprint deleted all their ZSH plugins, so find mirrors for the following repos

 * [x] [declare-zsh](https://github.com/zdharma/declare-zsh) - A command-line parser for Zinit commands in `zshrc`.~
 * [x] [diff-so-fancy](https://github.com/zdharma/zsh-diff-so-fancy) - Simplify installing the `diff-so-fancy` project into your user account. ~
  * [x] [editing-workbench](https://github.com/psprint/zsh-editing-workbench) - Adds sane, complex command line editing (e.g. incremental history _word_ completion).
  * [x] [history-search-multi-word](https://github.com/zdharma/history-search-multi-word) - A syntax highlighted, multi-word history searcher for ZSH, bound to Ctrl-R, with advanced functions (e.g. bump of history entry to top of history).
  * [x] [navigation-tools](https://github.com/psprint/zsh-navigation-tools) - Adds `htop`-like `kill`, directory bookmarks browser, multi-word incremental history searcher and more.
  * [x] [startify](https://github.com/zdharma/zsh-startify) - vim-startify -like plugin for ZSH.
  * [x] [tig](https://github.com/zdharma/zsh-tig-plugin) - Adds a few advanced bindings and also provides a ZSH-rewritten function and/or script `tig-pick`.
  * [x] [z-a-bin-gem-node](https://github.com/zinit-zsh/z-a-bin-gem-node) - [Zinit](https://github.com/zdharma-continuum/zinit) extension that exposes binaries without altering `$PATH`, installs Ruby gems and Node modules and easily exposes their binaries, and updates the gems and modules when the associated plugin or snippet is updated.
  * [x] [z-a-man](https://github.com/zinit-zsh/z-a-man) - [Zinit](https://github.com/zdharma-continuum/zinit) extension that generates man pages for all plugins and snippets.
  * [x] [z-a-meta-plugins](https://github.com/zinit-zsh/z-a-meta-plugins) - Install groups of plugins with a single label ([Zinit](https://github.com/zdharma/zinit) only).
  * [x] [z-a-patch-dl](https://github.com/zinit-zsh/z-a-patch-dl) - [Zinit](https://github.com/zdharma/zinit) extension that downloads files and applies patches through the provided `dl''` and `patch''` ices.
  * [x] [z-a-rust](https://github.com/zinit-zsh/z-a-rust) - [Zinit](https://github.com/zdharma/zinit) extension that that installs rust and cargo packages inside plugin directories.
  * [x] [z-a-submods](https://github.com/zinit-zsh/z-a-submods) - [Zinit](https://github.com/zdharma/zinit) extenstion allows installing and managing additional submodules within a plugin or snippet.
  * [x] [z-a-test](https://github.com/zinit-zsh/z-a-test) - [Zinit](https://github.com/zdharma/zinit) extension that runs tests (via `make test`, for example) – if it finds any of them – after installing and updating a plugin or snippet.
  * [x] [z-a-unscope](https://github.com/zinit-zsh/z-a-unscope) - Allows installing plugins for [Zinit](https://github.com/zdharma/zinit) without specifying the user name by querying the Github API.
  * [x] [zconvey](https://github.com/zdharma/zconvey) - Adds ability to send commands to other ZSH sessions, you can use this to `cd $PWD` on all active Z shell sessions, for example.
  * [x] [zflai](https://github.com/zdharma/zflai) - A fast logging framework for ZSH.
  * [x] [zgdbm](https://github.com/zdharma/zgdbm) - Adds GDBM as a plugin.
  * [x] [zinit-configs](https://github.com/zdharma/zinit-configs) - Real-world configuration files (basically a collection of `.zshrc` files) holding Zinit invocations.
  * [x] [zredis](https://github.com/zdharma/zredis) - Adds Redis database support, with `database_key` <-> `shell_variable` binding. Supports all data types.
  * [x] [zsnapshot](https://github.com/psprint/zsnapshot) - Adds command to dump the current ZSH state into a file, for later restoration by sourcing the snapshot file.
  * [x] [ztrace](https://github.com/psprint/ztrace) - Catches output of commands, allows to reuse that output, glue it with history content.
  * [x] [zui](https://github.com/zdharma/zui/) - ZSH User Interface library – CGI+DHTML-like rapid TUI application development with ZSH.

**Comment by pschmitt** [comment]
I migrated z-a-man to the zdharma-continuum org

**Comment by alichtman** [comment]
I wrote my own [`zsh-startify`](https://github.com/alichtman/zsh-startify). It's in python, so it's way slower than it could be (may rewrite it in Rust), but it works nicely.

**Comment by pschmitt** [comment]
A few more repos you can check off of your list:

- https://github.com/zdharma-continuum/zsh-github-issues
- https://github.com/zdharma-continuum/zsh-startify
- https://github.com/zdharma-continuum/zinit-configs
- https://github.com/zdharma-continuum/z-a-test

Thanks to @NorthIsMirror
