### ISSUE TITLE
Find a mirror for psprint's github-issues plugin

### ISSUE THREAD

**Issue by unixorn** [unixorn/awesome-zsh-plugins#1337]
* [ ] [github-issues](https://github.com/zdharma/zsh-github-issues) - Subscribe to projects on Github and receive within shell (under prompt) notifications about new issues.

**Comment by LucasLarson** [comment]
When Google last cached `https://github.com/zdharma/zsh-github-issues` on 2021-10-24,[^1] the latest commit was still @psprint’s from 2019-12-15: `19530979ae5d6c9e48456deaf1ad282522f05c2a`.

That’s also the latest commit on @Jacke’s copy at [Jacke/zsh-github-issues](https://github.com/Jacke/zsh-github-issues/commits).[^2]

[^1]: [Google cache](https://webcache.googleusercontent.com/search?q=cache:eOExZ1QWNNoJ:https://github.com/zdharma/zsh-github-issues&hl=en&gl=us&strip=0&vwsrc=1) and [archive](https://archive.today/2021.10.24-125201/https://github.com/zdharma/zsh-github-issues) of Google cache
[^2]: [Zip at `1953097`](https://github.com/Jacke/zsh-github-issues/archive/19530979ae5d6c9e48456deaf1ad282522f05c2a.zip) and [archive](https://web.archive.org/web/20211109220442id_/codeload.github.com/Jacke/zsh-github-issues/zip/19530979ae5d6c9e48456deaf1ad282522f05c2a).

**Comment by unixorn** [comment]
Thanks, I'm going to re-add it now.
