### ISSUE TITLE
Find mirror of psprint's morpho plugin

### ISSUE THREAD

**Issue by unixorn** [unixorn/awesome-zsh-plugins#1338]
* [ ] [morpho](https://github.com/psprint/zsh-morpho) - Terminal screen savers written in pure ZSH, and also screen saver framework.

**Comment by LucasLarson** [comment]
I found two repositories whose most recent commits (`6de5232` on 2019-02-13)[^1][^2] match those of [the last commit at `origin` that the Wayback Machine has record of](https://web.archive.org/web/20201015155957/https://github.com/psprint/zsh-morpho).[^3]

[^1]: https://github.com/disco0/zsh-morpho/commits
[^2]: https://github.com/Jacke/zsh-morpho/commits
[^3]: This commit occurred on 2019-02-13, too. The page was archived on 2020-10-15.

**Comment by unixorn** [comment]
Thanks!
