### ISSUE TITLE
Find mirror of psprint's redis plugin

### ISSUE THREAD

**Issue by unixorn** [unixorn/awesome-zsh-plugins#1339]
* [ ] [redis](https://github.com/zservices/redis) - Will run `redis-server` pointing it to the `redis.conf` configuration file. This can be used with the [zdharma/zredis](https://github.com/zdharma/zredis) plugin to share variables between shells.

**Comment by ss-o** [comment]
:wave:

1. https://github.com/z-shell/zredis
2. https://github.com/z-shell/redis

> This can be used with the plugin https://github.com/z-shell/zredis to have the Redis-backend running.
