### ISSUE TITLE
Find mirror of psprint's select plugin

### ISSUE THREAD

**Issue by unixorn** [unixorn/awesome-zsh-plugins#1340]
* [ ] [select](https://github.com/psprint/zsh-select) - Multi-term searched selection list with approximate matching and uniq mode.

**Comment by ss-o** [comment]
Hey, :wave:

Is this the correct one?

https://github.com/z-shell/zsh-select

**Comment by unixorn** [comment]
It looks similar but there are no commits from psprint in it :-/

**Comment by ss-o** [comment]
Could you, double-check, please? :octocat:

**Comment by unixorn** [comment]
Doh! I'm not sure how I missed the psprint commits, my bad. Yes, this is the one I wanted to find.
