### ISSUE TITLE
my theme is listed as having git decorations but it does not

### ISSUE THREAD

**Issue by r-mohammadi1** [unixorn/awesome-zsh-plugins#1407]
lunachar, a theme i wrote, does not actually support git decorations. also i have recently grouped all my published zsh themes into a single repo, so links to the old ones might be broken. (i also wrote stellachar)

**Comment by unixorn** [comment]
Thanks, I'll update the description. Single repos make it easier for most frameworks to use a plugin/theme. What's the new repo name so I can update the other entries?

**Comment by r-mohammadi1** [comment]
The new repo is called armans-zsh-themes.   
  
  

  
>
