### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [unixorn/awesome-zsh-plugins#1722]
Hello, I found some broken hyperlinks:
- [ ] ohmyz.sh (file: README.md, status code: 404)
- [ ] https://www.refining-linux.org/archives/59-ZSH-Gem-24-ZSH-frameworks.html (file: README.md, status code: 500)
- [ ] code.jquery.com (file: README.md, status code: 404)
- [ ] omt-manager (file: README.md, status code: 404)
- [ ] https://github.com/cloudfoundry/bosh)%5D (file: README.md, status code: 404)
- [ ] brew.sh (file: README.md, status code: 404)
- [ ] https://buidler.dev (file: README.md, error: ERR_TLS_CERT_ALTNAME_INVALID)
- [ ] ohmyzsh/ohmyzsh (file: README.md, status code: 404)

**Comment by unixorn** [comment]
All the readme.md links you've marked as `404` are working when I check with a browser. What tool did you use to find them?

**Comment by ndsvw** [comment]
It's a custom tool based on https://github.com/tcort/markdown-link-check

The ones that don't start with https:// are interpreted as relative links.

There are multiple working brew.sh links, but the one here does not work:

![Screenshot_20230521_072007](https://github.com/unixorn/awesome-zsh-plugins/assets/21332313/e69a328c-7a45-438c-8686-ca03c9c74f97)

This one is the broken "ohmyzsh/ohmyzsh"...
![Screenshot_20230521_072221](https://github.com/unixorn/awesome-zsh-plugins/assets/21332313/eca599b4-3918-4195-ba88-79b84a3fa18d)


You are right about the bosh link (2nd one in the readme), but it's technically invalid markdown and therefore also not rendered correctly..
`Tab completion for [BOSH(https://github.com/cloudfoundry/bosh)]`
===> `Tab completion for [BOSH](https://github.com/cloudfoundry/bosh)` 
![Screenshot_20230521_073019](https://github.com/unixorn/awesome-zsh-plugins/assets/21332313/f424301f-db19-4ac7-a1fa-649467f66be9)
