### ISSUE TITLE
Remove `angry-fly-zsh`

### ISSUE THREAD

**Issue by hyperupcall** [unixorn/awesome-zsh-plugins#1781]
I am removing a
- [x] A link to an existing ZSH framework

**Link**: https://github.com/russjohnson/angry-fly-zsh

As per the [contributing](https://github.com/unixorn/awesome-zsh-plugins/blob/main/Contributing.md), this is an issue to discuss why [angry-fly-zsh](https://github.com/russjohnson/angry-fly-zsh) should be removed. The repository:

- Has not been updated in 10 years
- No longer has a working screenshot
- Has a low number of stars for not being updated in 10 years (3)
- Has no LICENSE (just another contributing factor, even though there are other entries without licenses)

**Comment by unixorn** [comment]
Agreed.
