### ISSUE TITLE
Remove link to `phpenv.plugin.zsh`

### ISSUE THREAD

**Issue by hyperupcall** [unixorn/awesome-zsh-plugins#1783]
**Link**: https://github.com/sptndc/phpenv.plugin.zsh

As per the [contributing](https://github.com/unixorn/awesome-zsh-plugins/blob/main/Contributing.md), this is an issue to discuss why [phpenv.plugin.zsh](https://github.com/sptndc/phpenv.plugin.zsh) should be removed. The repository:

- Hasn't been updated in 5 years
- Plugin code is rather short and can easily be hand-written given initialization instructions of phpenv
- is archived
- ~~depends on [phpenv](https://github.com/sptndc/phpenv), which also is archived~~
- has low star count for not being updatedin 5 years (2 stars)
- Has no LICENSE (just another contributing factor, even though there are other entries without licenses)

**Comment by unixorn** [comment]
Sounds like a valid scrub.
