### ISSUE TITLE
[LINK] tab-title

### ISSUE THREAD

**Issue by p1r473** [unixorn/awesome-zsh-plugins#1863]
I am submitting a

- [X] New plugin

tab-title
Updates current tab name in screen/tmux/byobu to whatever dir your in or command youre running
https://github.com/p1r473/tab-title/

**Comment by unixorn** [comment]
The plugin file hasn't been pushed to github yet. Comment on this issue when it's published, thanks!

**Comment by p1r473** [comment]
@unixorn whoops sorry bout that! done now

**Comment by p1r473** [comment]
@unixorn whoops sorry bout that! done now

**Comment by p1r473** [comment]
@unixorn whoops sorry bout that! done now

**Comment by p1r473** [comment]
@unixorn bump!

**Comment by unixorn** [comment]
The link is 404 - I already added your window-title plugin, did you rename the tab-title repo?

**Comment by p1r473** [comment]
@unixorn Fixed!
