### ISSUE TITLE
Add IconicFonts

### ISSUE THREAD

**Issue by mdSlash** [unixorn/awesome-zsh-plugins#1897]
I am submitting a
- [x] New utility

Hi there! I’ve created patched fonts with over 60,000 icons specifically for TUI projects. Can I submit a pull request to include [IconicFonts](https://github.com/iconicFonts/iconic-fonts) repository in awesome-zsh-plugins?

**Comment by mdSlash** [comment]
It seems a bit off-topic

**Comment by unixorn** [comment]
If it's not a font someone would reasonably use in their terminal, it would be off-topic.
