### ISSUE TITLE
[LINK] zsh-chezmoi

### ISSUE THREAD

**Issue by mass8326** [unixorn/awesome-zsh-plugins#1898]
I am submitting a
- [x] New plugin

Link: https://github.com/mass8326/zsh-chezmoi
- [x] Has readme
- [x] Has license

zsh-chezmoi adds completion and several aliases that makes using [chezmoi](https://www.chezmoi.io/), especially chezmoi's [git subcommands](https://www.chezmoi.io/reference/commands/git/), easier.

**Comment by unixorn** [comment]
Thanks! Adding in today's update.
