### ISSUE TITLE
[LINK] zsh-bws plugin

### ISSUE THREAD

**Issue by msarti** [unixorn/awesome-zsh-plugins#1917]
Link: https://github.com/elogiclab/zsh-bws

I am submitting a
- [ ] Article link - something useful to ZSH users
- [ ] A link to a new ZSH framework
- [X] New plugin
- [ ] New theme
- [ ] New tab completion
- [ ] New utility

This plugin introduces some useful features to access Bitwarden Secrets Manager via its command line utility `bws`.

**Comment by unixorn** [comment]
Added in https://github.com/unixorn/awesome-zsh-plugins/pull/1918
