### ISSUE TITLE
[LINK] zsh-ai-completions

### ISSUE THREAD

**Issue by iloveitaly** [unixorn/awesome-zsh-plugins#1920]
I am submitting a:

- [ ] Article link - something useful to ZSH users
- [ ] A link to a new ZSH framework
- [  ] New plugin
- [  ] New theme
- [ x] New tab completion
- [  ] New utility

https://github.com/iloveitaly/zsh-ai-completions

**Comment by unixorn** [comment]
I added https://github.com/iloveitaly/zsh-ai-completions/issues/1 before I saw this issue. Close that when you've added a license and I will add this completion. I love the idea of making completions easier to write by letting the AI do the boring bit.

**Comment by iloveitaly** [comment]
Just added a license!
