### ISSUE TITLE
How do you find things so quickly?

### ISSUE THREAD

**Issue by jedahan** [unixorn/awesome-zsh-plugins#566]
Do you just search for all repositories that have a file with .zsh extension and check them? Get an email digest? Look for tags?

<3

**Comment by unixorn** [comment]
Most mornings I do a GitHub search for zsh plugin or zsh theme while I'm having coffee and order it by recently updated.

**Comment by jedahan** [comment]
thanks for the hard work!

**Comment by unixorn** [comment]
You're welcome!
