### ISSUE TITLE
Add new plugin to list

### ISSUE THREAD

**Issue by lfromanini** [unixorn/awesome-zsh-plugins#643]
Hello, can you please add my plugin to your list?

omz-hist: Provides convenient alias to examine your command line history in Zsh.
https://github.com/lfromanini/omz-hist

Thanks in advance!

**Comment by unixorn** [comment]
Sorry I missed this issue - just went to look at it and the repo is missing.

**Comment by lfromanini** [comment]
Yes, I dropped it some time ago. I realize it wasn't good enough. If you can use this link, instead, seams more solid: [https://github.com/lfromanini/sshWrapper](https://github.com/lfromanini/sshWrapper)

Thanks in advance!

**Comment by unixorn** [comment]
I'm curious - why use that instead of public key auth?

**Comment by lfromanini** [comment]
In my scenario, it's a very particular use case. I have an environment with more than 1000 VMs, being redeployed every three weeks. I have to connect to some then (usually, I don't know which one until I need to). To deploy my ssh key over all VMs will be an overkill. Usually, I just need one access to check some logs. It's a test environment with a common user/pass shared across several users and security is not an issue at all (since it's a short living test env).

I fully understand the security implications of this approach and added a note in README.md so all users can be aware.
