### ISSUE TITLE
Remove abandoned frameworks

### ISSUE THREAD

**Issue by equal-l2** [unixorn/awesome-zsh-plugins#685]
Here I define an "abandoned" project as one which has no update for over a year.   

- [antigen-hs](https://github.com/Tarrasch/antigen-hs) (no update since 2016, 188 stars)
- [dotzsh](https://github.com/dotphiles/dotzsh) (no update since 2015, 167 stars)
- [pumice](https://github.com/ryutamaki/pumice) (no update since 2015, 6 stars)
- [zapack](https://github.com/aiya000/zsh-zapack) (no update since 2017, no star)
- [zilsh](https://github.com/zilsh/zilsh) (no update since 2014, 28 stars)
- [zpacker](https://github.com/happyslowly/zpacker) (no update since 2017, 2 stars)
- [ztanesh](https://github.com/miohtama/ztanesh) (no update since 2015, 256 stars)

**Comment by unixorn** [comment]
Some of these may just be stable.

It might be better to add a last-commit badge to the framework entries like I do for the list itself ```[![GitHub last commit (branch)](https://img.shields.io/github/last-commit/unixorn/awesome-zsh-plugins/master.svg)](https://github.com/unixorn/awesome-zsh-plugins)`` to show the last commit date for each of the frameworks?
