### ISSUE TITLE
Have human-clickable link in PR template?

### ISSUE THREAD

**Issue by jedahan** [unixorn/awesome-zsh-plugins#772]
I often click a PR, then go to changes, then copy-paste the link, then look at the page.

It would be cool if the PR template included a link to the upstream projects if they are new.

How do you feel about this?

**Comment by unixorn** [comment]
I used to do that, I suppose I could go back to that format. I'm not going to require other people to do it in their PRs though, I want to minimize the friction to contribute.

**Comment by unixorn** [comment]
Now that I've had a coffee, I think what you meant was to automatically include that - as far as I'm aware, there isn't an option to include the diff of the PR into the PR template.

If I'm wrong, let me know or PR the PR template.

Thanks!
