### ISSUE TITLE
Loading is a madness

### ISSUE THREAD

**Issue by denysdovhan** [unixorn/awesome-zsh-plugins#83]
Maybe better to remove badges for plugins and themes, because the loading takes about 20-30 sec. (or even more!) and after that I see something like this:

![image](https://cloud.githubusercontent.com/assets/3459374/13557037/91c0491c-e3f0-11e5-98fe-7574796f62f9.png)

I realize, it's a nice to see how many stars have a specific project, but it really turns the loading in a madness.

**Comment by voronkovich** [comment]
:+1:

**Comment by unixorn** [comment]
I think I'm going to yank the stars from all but the frameworks. I think it's a useful signal for frameworks, but the combination of slow page loads and false failures on the travis builds is driving me a little nuts.
